### PR TITLE
linkedin id changes

### PR DESCRIPTION
**Pull request by Apoorva2696**

### CODE REVIEW

**Review by Rucha1499 — APPROVED** [review]
Thank you!!

**Review by swarajpure — CHANGES_REQUESTED** [review]
Twitter account says it doesn't exist. Please fix it and we'll be good to go.

**Comment by Apoorva2696** [comment]
> Twitter account says it doesn't exist. Please fix it and we'll be good to go.

Done

**Review by swarajpure — APPROVED** [review]
Thank you!

Please make sure to tag the reviewers on the discord server so that they get to know the changes have been done. Otherwise they may get missed.

**Pull request merged**
