### PR TITLE
Added new member

### PR DESCRIPTION
**Pull request by RohitKuwar**
@swarajpure added new member

### CODE REVIEW

**Review by ankushdharkar — CHANGES_REQUESTED** [review]
- Image rules not followed. Face should be centered and 60% coverage
- mapping.json entry missing, please refer other accepted PRs

**Comment by RohitKuwar** [comment]
@ankushdharkar changes has been made please check.

**Review by ankushdharkar — CHANGES_REQUESTED** [review]
Image is not a square. Please check again (387 X 391)

**Comment by RohitKuwar** [comment]
@ankushdharkar Image has been resized to required size. Please check.

**Review by ankushdharkar — APPROVED** [review]

**Pull request merged**
