### PR TITLE
Adding Akanksha Dharkar to members mapping

### PR DESCRIPTION
**Pull request by akankshadharkar**

### CODE REVIEW

**Review by ankushdharkar — CHANGES_REQUESTED** [review]
Please upload another picture

Rule not met:
> Face should cover at least 60% of the image

Rules here: https://github.com/Real-Dev-Squad/website-static#rules-for-profile-picture

**Review by ankushdharkar — CHANGES_REQUESTED** [review]
@akankshadharkar Image is not a square. It's currently 357px X 315px. Please fix it and make it a square

**Comment by akankshadharkar** [comment]
Changed the ratio to 315px X 315px, please review

**Review by ankushdharkar — CHANGES_REQUESTED** [review]
Picture is blurry. Please add a better image @akankshadharkar

**Pull request closed without merging**
