### PR TITLE
Merge Branch

### PR DESCRIPTION
**Pull request by aman7870**
new member add

### CODE REVIEW

**Review by swarajpure — CHANGES_REQUESTED** [review]
Great! Thanks for sending your PR! 😄 

Just some changes:
Please add your RDS-id and github-id in `mapping.json`

Also, please make sure the image is square as stated here: https://github.com/Real-Dev-Squad/website-static#rules-for-profile-picture

**Comment by aman7870** [comment]
changed do check

**Review by swarajpure — CHANGES_REQUESTED** [review]
>Images should be a square
Size of the image should be greater than 500px X 500px
The face should be visible, centered and identifiable
Face should cover at least 60% of the image

Source: https://github.com/Real-Dev-Squad/website-static#rules-for-profile-picture

**Review by swarajpure — CHANGES_REQUESTED** [review]
Hello,
Though the image is (almost) square, your face is not covering 60% of it. Please see how others have their photos on the members page, if your PR gets merged, your photo would be the odd one out 😅 
Hope you get that.
image


Also, the folder name should be same as your RDS-id. It should be `/members/amanA` instead of `/members/aman`.

**Review by swarajpure — APPROVED** [review]
Great! Thank you 🎉

**Pull request merged**
